/**
 * Generates lib/blur-data.ts — a map of public image path to a tiny inline
 * JPEG used as next/image's `blurDataURL`.
 *
 *   node scripts/generate-blur.mjs
 *
 * Run this after adding or re-encoding catalogue photography. The previews are
 * ~12px wide, so the whole map costs a couple of kilobytes and ships inline
 * rather than as extra requests.
 */

import sharp from "sharp";
import { readFile, readdir, writeFile } from "fs/promises";
import { join, extname } from "path";
import { fileURLToPath } from "url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DIRS = ["plants", "bg"];
const WIDTH = 12;

const entries = [];

for (const dir of DIRS) {
  const abs = join(ROOT, "public", dir);
  for (const name of (await readdir(abs)).sort()) {
    if (![".jpg", ".jpeg", ".png"].includes(extname(name).toLowerCase())) continue;
    const buf = await sharp(await readFile(join(abs, name)))
      .resize(WIDTH)
      .jpeg({ quality: 40 })
      .toBuffer();
    entries.push([`/${dir}/${name}`, `data:image/jpeg;base64,${buf.toString("base64")}`]);
  }
}

const file = `// Generated by scripts/generate-blur.mjs — do not edit by hand.
// Tiny inline previews shown while the real image loads.

export const BLUR_DATA: Record<string, string> = {
${entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")}
};

/** next/image needs both \`placeholder\` and \`blurDataURL\`, and passing
 *  \`placeholder="blur"\` without the data throws. Spread this instead. */
export function blurProps(src: string) {
  const blurDataURL = BLUR_DATA[src];
  return blurDataURL ? { placeholder: "blur" as const, blurDataURL } : {};
}
`;

await writeFile(join(ROOT, "lib", "blur-data.ts"), file);
console.log(
  `wrote lib/blur-data.ts — ${entries.length} previews, ${(
    file.length / 1024
  ).toFixed(1)} KB`
);
